# Generated by Django 5.2 on 2025-04-06 14:54

from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Greeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "when",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("account_source", models.CharField(max_length=255)),
                ("created_date", models.DateTimeField()),
                ("account_id", models.CharField(max_length=18, unique=True)),
                ("industry", models.CharField(max_length=255)),
                ("is_deleted", models.BooleanField()),
                ("name", models.CharField(max_length=255)),
                ("system_modstamp", models.DateTimeField()),
            ],
        ),
    ]
