# Generated by Django 5.2.1 on 2025-05-30 00:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
