# Generated by Django 5.2.1 on 2025-05-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_newsarticle_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={},
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='slug',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='newsarticle',
            table=None,
        ),
    ]
