# Generated by Django 5.2.1 on 2025-05-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_newsarticle_options_remove_newsarticle_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
